@echo off
echo [*] Stopping Explorer and dllhost...
taskkill /f /im explorer.exe 2>nul
taskkill /f /im dllhost.exe 2>nul

echo [*] Unregistering StitchPeek.dll...
regsvr32.exe /u /s "build\Release\StitchPeek.dll"

echo [*] Clearing Windows Thumbnail Cache database...
del /F /A /Q "%LocalAppData%\Microsoft\Windows\Explorer\thumbcache_*.db" 2>nul

echo [*] Restarting Windows Explorer...
start explorer.exe

echo [*] Maintenance Complete.
echo StitchPeek has been completely uninstalled from your registry. 
echo You can now test the Setup Installer (.exe) generated by Inno Setup from a clean environment!
pause
